Rss frontend
oth-datapipeline/analysis pull request #8
Opened 2022-06-26 15:15 UTC by lukasgraef

Implemented eleven analyses for RSS
Some are visualized using bar charts, two also offer a wordcloud visualization

2022-06-27 07:53 UTC, dim35216 approved these changes, later dismissed

2022-06-27 08:04 UTC, bastistrasser commented on src/analyzers/rss_analyzer.py
> +from unittest import result
unused import

2022-06-27 08:04 UTC, bastistrasser requested changes
The implemented analyses look good, just two little remarks:
- Add docstrings to the implemented methods (most importantly in the rss analyzer where the analysis is described shortly)
- Adjust requirements_linux.txt

2022-06-27 08:52 UTC, bastistrasser commented on src/analyzers/rss_analyzer.py
>          limit = int(st.text_input("Limit", value="100"))
maybe add a checkbox or radio button for allowing to sort the similiarities in descending/ascending order instead of implementing two methods here for similiarity and dissimiliarity? Just an idea, you can also leave it like it is if you prefer the current implementation

2022-06-28 18:30 UTC, bastistrasser approved these changes

2022-06-28 18:30 UTC, merged